name: dither_it
description: DitherIt is a Dart library that implements various dithering algorithms.
version: 0.0.1
homepage: https://github.com/Penfore/dither_it

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <5.0.0"
flutter:
